# Generated by Django 3.2.4 on 2021-08-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
    ]
