# Generated by Django 3.2.4 on 2021-08-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0002_remove_comment_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailToAdmin',
        ),
    ]
